<?php
    include_once("../../../model/model.php");
    $md=new ProgramModel;
    require_once('../../../TCPDF/tcpdf.php');
    class MyPDF extends TCPDF {
        public function Footer() {
            $currentPage = $this->getAliasNumPage();
            $totalPages = $this->getAliasNbPages();
            $format = 'Página ' . $currentPage . ' de ' . $totalPages;
            $this->SetY(-15);
            $this->SetFont('helvetica', 'I', 8);
            $this->Cell(0, 10, $format, 0, 0, 'C');
        }
    }
    $pdf = new MyPDF('L', 'mm', 'Letter', true, 'UTF-8', false);
    $pdf->SetPrintHeader(false);
    $pdf->SetCreator('Eliud Abraham Español Astudillo');
    $pdf->SetAuthor('Eliud Abraham Español Astudillo');
    $pdf->SetTitle('Reporte de Docente');
    $pdf->SetSubject('Reporte General de Docentes');
    $pdf->SetKeywords('PDF, TCPDF, PHP');
    $pageWidth = $pdf->GetPageWidth();
    $cellWidth = $pageWidth - ($pdf->getMargins()['left'] + $pdf->getMargins()['right']);
    $cellX = $pdf->getMargins()['left'];
    $cellY = $pdf->getMargins()['top'];
    $pdf->SetXY($cellX, $cellY);
    foreach ($_POST['lista_reporte'] as $indice => $opcion){
        $nreporte=' (Reporte:'.($indice+1).' de: '.count($_POST['lista_reporte']).")";
        $pdf->AddPage();
        $sql="SELECT * FROM parte_mensual WHERE id = ".$opcion;
        $parte=$md->capturar($sql);
        $sql="SELECT * FROM centro WHERE id_centro =".$parte[0]["id_centro"];
        $centro=$md->capturar($sql);
        $sql="SELECT * FROM docente_parte_mensual WHERE id_parte_mensual = $opcion";
        $docentes=$md->capturar($sql);
        $sql="SELECT * FROM detalle_parte_mensual WHERE id_parte_mensual = $opcion";
        $detalles=$md->capturar($sql);
        $sql="SELECT concat(Nombre1,' ',Nombre2,' ',Apellido1,' ',Apellido2) as nombre, Telefono FROM docente WHERE id=".$parte[0]['director'];
        $director=$md->capturar($sql);
        $pdf->SetFont('helvetica', 'B', 17);
        $pdf->Cell($cellWidth, 8, 'Dirección De Educación Departemental De: Yoro'.$nreporte, 0, 1, 'C', false, '', 0, false, 'T', 'C');
        $pdf->SetFont('helvetica', 'B', 14);
        $pdf->Cell($cellWidth, 6, 'Dirección Municipal De: '.$centro[0]['Municipio'], 0, 1, 'C', false, '', 0, false, 'T', 'C');
        $pdf->Cell($cellWidth, 6, 'Parte Mensual Mes De:'.$parte[0]['mes'].' De: '.$parte[0]['anno'], 0, 1, 'C', false, '', 0, false, 'T', 'C');
        $pdf->ln(2);
        $pdf->SetFont('helvetica', "B" ,12);
        $pdf->Cell(50, 7, 'Nombre Del Centro:', 0, 0, 'L');
        $pdf->SetFont('helvetica', 'U', 12);
        $pdf->Cell(90, 7,$centro[0]['Nombre'], 0, 0);
        $pdf->SetFont('helvetica', "B" ,12);
        $pdf->Cell(40, 7, 'Direccion:', 0, 0, 'L');
        $pdf->SetFont('helvetica', 'U', 12);
        $pdf->Cell(100, 7,$centro[0]['Direccion'], 0, 1);
        $pdf->SetFont('helvetica', "B" ,12);
        $pdf->Cell(50, 7, 'Codigo Del Centro:', 0, 0, 'L');
        $pdf->SetFont('helvetica', 'U', 12);
        $pdf->Cell(90, 7,$centro[0]['Codigo_centro'], 0, 0);
        $pdf->SetFont('helvetica', "B" ,12);
        $pdf->Cell(40, 7, 'Tipo de Centro:', 0, 0, 'L');
        $pdf->SetFont('helvetica', 'U', 12);
        $pdf->Cell(100, 7,$centro[0]['Tipo_centro'], 0, 1);
        $pdf->SetFont('helvetica', "B" ,12);
        $pdf->Cell(50, 7, 'Nombre del Director:', 0, 0, 'L');
        $pdf->SetFont('helvetica', 'U', 12);
        $pdf->Cell(90, 7,$director[0]['nombre'], 0, 0);
        $pdf->SetFont('helvetica', "B" ,12);
        $pdf->Cell(40, 7, 'Celular:', 0, 0, 'L');
        $pdf->SetFont('helvetica', 'U', 12);
        $pdf->Cell(100, 7,$director[0]['Telefono'], 0, 1);
        $pdf->SetFont('helvetica', "B" ,12);
        $pdf->Cell(55, 7, 'N° Docentes Femeninos:', 0, 0, 'L');
        $pdf->SetFont('helvetica', 'U', 12);
        $pdf->Cell(10, 7,$parte[0]['doc_fem'], 0, 0);
        $pdf->SetFont('helvetica', "B" ,12);
        $pdf->Cell(55, 7, 'N° Docentes Masculinos:', 0, 0, 'L');
        $pdf->SetFont('helvetica', 'U', 12);
        $pdf->Cell(10, 7,$parte[0]['doc_mas'], 0 , 0);
        $pdf->SetFont('helvetica', "B" ,12);
        $pdf->Cell(50, 7, 'Total de Docentes', 0, 0, 'L');
        $pdf->SetFont('helvetica', 'U', 12);
        $pdf->Cell(10, 7,$parte[0]['tot_doc'], 0, 0);
        $pdf->SetFont('helvetica', "B" ,12);
        $pdf->Cell(50, 7, 'Dias Trabajados', 0, 0, 'L');
        $pdf->SetFont('helvetica', 'U', 12);
        $pdf->Cell(10, 7,$parte[0]['dias_trab'], 0, 1,'L');
        $pdf->ln(4);
        $pdf->Cell(15, 12, "Grado", 1, 0, 'C');
        $pdf->SetFillColor(255, 255, 255);
        $pdf->MultiCell(30, 12, "Matricula Consolidada", 1, 'C');
        $x = $pdf->GetX();
        $y = $pdf->GetY();
        $pdf->SetXY($x + 45, $y - 12);
        $pdf->SetFillColor(255, 255, 255);
        $pdf->MultiCell(30, 12, "Matricula Anterior", 1, 'C');
        $pdf->SetXY($x + 75, $y - 12);
        $pdf->MultiCell(30, 12, "Matricula Actual", 1, 'C');
        $pdf->SetXY($x + 105, $y - 12);
        $pdf->MultiCell(30, 12, "Asistencia Media", 1, 'C');
        $pdf->SetXY($x + 135, $y - 12);
        $pdf->MultiCell(30, 12, "Tanto Porciento", 1, 'C');
        $pdf->SetXY($x + 165, $y - 12);
        $pdf->Cell(30, 12, "Inasistencias", 1, 0, 'C');
        $pdf->Cell(30, 12, "Ingresos", 1, 0, 'C');
        $pdf->Cell(30, 12, "Desertores", 1, 0, 'C');
        $pdf->Cell(30, 12, "Traslados", 1, 1, 'C');
        $pdf->SetFont('helvetica', '', 10);
        $pdf->Cell(15, 5, "", 1, 0, 'C');
        $pdf->Cell(10, 5, "N", 1, 0, 'C');
        $pdf->Cell(10, 5, "V", 1, 0, 'C');
        $pdf->Cell(10, 5, "T", 1, 0, 'C');
        $pdf->Cell(10, 5, "N", 1, 0, 'C');
        $pdf->Cell(10, 5, "V", 1, 0, 'C');
        $pdf->Cell(10, 5, "T", 1, 0, 'C');
        $pdf->Cell(10, 5, "N", 1, 0, 'C');
        $pdf->Cell(10, 5, "V", 1, 0, 'C');
        $pdf->Cell(10, 5, "T", 1, 0, 'C');
        $pdf->Cell(10, 5, "N", 1, 0, 'C');
        $pdf->Cell(10, 5, "V", 1, 0, 'C');
        $pdf->Cell(10, 5, "T", 1, 0, 'C');
        $pdf->Cell(10, 5, "N", 1, 0, 'C');
        $pdf->Cell(10, 5, "V", 1, 0, 'C');
        $pdf->Cell(10, 5, "T", 1, 0, 'C');
        $pdf->Cell(10, 5, "N", 1, 0, 'C');
        $pdf->Cell(10, 5, "V", 1, 0, 'C');
        $pdf->Cell(10, 5, "T", 1, 0, 'C');
        $pdf->Cell(10, 5, "N", 1, 0, 'C');
        $pdf->Cell(10, 5, "V", 1, 0, 'C');
        $pdf->Cell(10, 5, "T", 1, 0, 'C');
        $pdf->Cell(10, 5, "N", 1, 0, 'C');
        $pdf->Cell(10, 5, "V", 1, 0, 'C');
        $pdf->Cell(10, 5, "T", 1, 1, 'C');
        $pdf->SetXY($x+255, $y);
        $pdf->Cell(10, 5, "N", 1, 0, 'C');
        $pdf->Cell(10, 5, "V", 1, 0, 'C');
        $pdf->Cell(10, 5, "T", 1, 1, 'C');
        $pdf->SetFont('helvetica', '', 10);
        $mat_con_hem=0;
        $mat_con_var=0;
        $mat_con_tot=0;
        $mat_ant_hem=0;
        $mat_ant_var=0;
        $mat_ant_tot=0;
        $mat_act_hem=0;
        $mat_act_var=0;
        $mat_act_tot=0;
        $asis_med_hem=0;
        $asis_med_var=0;
        $asis_med_tot=0;
        $tant_porc_hem=0;
        $tant_porc_var=0;
        $tant_porc_tot=0;
        $inasistencia_hem=0;
        $inasistencia_var=0;
        $inasistencia_tot=0;
        $ingreso_hem=0;
        $ingreso_var=0;
        $ingreso_tot=0;
        $desertores_hem=0;
        $desertores_var=0;
        $desertores_tot=0;
        $traslados_hem=0;
        $traslados_var=0;
        $traslados_tot=0;
        foreach ($detalles as $detalle) {
            if (trim($detalle['grado']) == "Subtotal") {
                $pdf->SetFillColor(50, 200, 255);
                $mat_con_hem=$mat_con_hem+$detalle["mat_con_hem"];
                $mat_con_var=$mat_con_var+$detalle["mat_con_var"];
                $mat_con_tot=$mat_con_tot+$detalle["mat_con_tot"];
                $mat_ant_hem=$mat_ant_hem+$detalle["mat_ant_hem"];
                $mat_ant_var=$mat_ant_var+$detalle["mat_ant_var"];
                $mat_ant_tot=$mat_ant_tot+$detalle["mat_ant_tot"];
                $mat_act_hem=$mat_act_hem+$detalle["mat_act_hem"];
                $mat_act_var=$mat_act_var+$detalle["mat_act_var"];
                $mat_act_tot=$mat_act_tot+$detalle["mat_act_tot"];
                $asis_med_hem=$asis_med_hem+$detalle["asis_med_hem"];
                $asis_med_var=$asis_med_var+$detalle["asis_med_var"];
                $asis_med_tot=$asis_med_tot+$detalle["asis_med_tot"];
                $tant_porc_hem=$tant_porc_hem+$detalle["tant_porc_hem"];
                $tant_porc_var=$tant_porc_var+$detalle["tant_porc_var"];
                $tant_porc_tot=$tant_porc_tot+$detalle["tant_porc_tot"];
                $inasistencia_hem=$inasistencia_hem+$detalle["inasistencia_hem"];
                $inasistencia_var=$inasistencia_var+$detalle["inasistencia_var"];
                $inasistencia_tot=$inasistencia_tot+$detalle["inasistencia_tot"];
                $ingreso_hem=$ingreso_hem+$detalle["ingreso_hem"];
                $ingreso_var=$ingreso_var+$detalle["ingreso_var"];
                $ingreso_tot=$ingreso_tot+$detalle["ingreso_tot"];
                $desertores_hem=$desertores_hem+$detalle["desertores_hem"];
                $desertores_var=$desertores_var+$detalle["desertores_var"];
                $desertores_tot=$desertores_tot+$detalle["desertores_tot"];
                $traslados_hem=$traslados_hem+$detalle["traslados_hem"];
                $traslados_var=$traslados_var+$detalle["traslados_var"];
                $traslados_tot=$traslados_tot+$detalle["traslados_tot"];
            }else{
                $pdf->SetFillColor(250, 250, 250);
            }
            $pdf->Cell(15, 8, $detalle['grado'], 1, 0, 'C',true);
            $pdf->Cell(10, 8, $detalle['mat_con_hem'], 1, 0, 'C',true);
            $pdf->Cell(10, 8, $detalle['mat_con_var'], 1, 0, 'C',true);
            $pdf->Cell(10, 8, $detalle['mat_con_tot'], 1, 0, 'C',true);
            $pdf->Cell(10, 8, $detalle['mat_ant_hem'], 1, 0, 'C',true);
            $pdf->Cell(10, 8, $detalle['mat_ant_var'], 1, 0, 'C',true);
            $pdf->Cell(10, 8, $detalle['mat_ant_tot'], 1, 0, 'C',true);
            $pdf->Cell(10, 8, $detalle['mat_act_hem'], 1, 0, 'C',true);
            $pdf->Cell(10, 8, $detalle['mat_act_var'], 1, 0, 'C',true);
            $pdf->Cell(10, 8, $detalle['mat_act_tot'], 1, 0, 'C',true);
            $pdf->Cell(10, 8, $detalle['asis_med_hem'], 1, 0, 'C',true);
            $pdf->Cell(10, 8, $detalle['asis_med_var'], 1, 0, 'C',true);
            $pdf->Cell(10, 8, $detalle['asis_med_tot'], 1, 0, 'C',true);
            $pdf->Cell(10, 8, $detalle['tant_porc_hem'], 1, 0, 'C',true);
            $pdf->Cell(10, 8, $detalle['tant_porc_var'], 1, 0, 'C',true);
            $pdf->Cell(10, 8, $detalle['tant_porc_tot'], 1, 0, 'C',true);
            $pdf->Cell(10, 8, $detalle['inasistencia_hem'], 1, 0, 'C',true);
            $pdf->Cell(10, 8, $detalle['inasistencia_var'], 1, 0, 'C',true);
            $pdf->Cell(10, 8, $detalle['inasistencia_tot'], 1, 0, 'C',true);
            $pdf->Cell(10, 8, $detalle['ingreso_hem'], 1, 0, 'C',true);
            $pdf->Cell(10, 8, $detalle['ingreso_var'], 1, 0, 'C',true);
            $pdf->Cell(10, 8, $detalle['ingreso_tot'], 1, 0, 'C',true);
            $pdf->Cell(10, 8, $detalle['desertores_hem'], 1, 0, 'C',true);
            $pdf->Cell(10, 8, $detalle['desertores_var'], 1, 0, 'C',true);
            $pdf->Cell(10, 8, $detalle['desertores_tot'], 1, 0, 'C',true);
            $pdf->Cell(10, 8, $detalle['traslados_hem'], 1, 0, 'C',true);
            $pdf->Cell(10, 8, $detalle['traslados_var'], 1, 0, 'C',true);
            $pdf->Cell(10, 8, $detalle['traslados_tot'], 1, 1, 'C',true);
        }
        $pdf->SetFillColor(250, 250, 0);
        $pdf->Cell(15, 8, 'TOTAL', 1, 0, 'C', true);
        $pdf->Cell(10, 8, $mat_con_hem, 1, 0, 'C', true);
        $pdf->Cell(10, 8, $mat_con_var, 1, 0, 'C', true);
        $pdf->Cell(10, 8, $mat_con_tot, 1, 0, 'C', true);
        $pdf->Cell(10, 8, $mat_ant_hem, 1, 0, 'C', true);
        $pdf->Cell(10, 8, $mat_ant_var, 1, 0, 'C', true);
        $pdf->Cell(10, 8, $mat_ant_tot, 1, 0, 'C', true);
        $pdf->Cell(10, 8, $mat_act_hem, 1, 0, 'C', true);
        $pdf->Cell(10, 8, $mat_act_var, 1, 0, 'C', true);
        $pdf->Cell(10, 8, $mat_act_tot, 1, 0, 'C', true);
        $pdf->Cell(10, 8, $asis_med_hem, 1, 0, 'C', true);
        $pdf->Cell(10, 8, $asis_med_var, 1, 0, 'C', true);
        $pdf->Cell(10, 8, $asis_med_tot, 1, 0, 'C', true);
        $pdf->Cell(10, 8, $tant_porc_hem, 1, 0, 'C', true);
        $pdf->Cell(10, 8, $tant_porc_var, 1, 0, 'C', true);
        $pdf->Cell(10, 8, $tant_porc_tot, 1, 0, 'C', true);
        $pdf->Cell(10, 8, $inasistencia_hem, 1, 0, 'C', true);
        $pdf->Cell(10, 8, $inasistencia_var, 1, 0, 'C', true);
        $pdf->Cell(10, 8, $inasistencia_tot, 1, 0, 'C', true);
        $pdf->Cell(10, 8, $ingreso_hem, 1, 0, 'C', true);
        $pdf->Cell(10, 8, $ingreso_var, 1, 0, 'C', true);
        $pdf->Cell(10, 8, $ingreso_tot, 1, 0, 'C', true);
        $pdf->Cell(10, 8, $desertores_hem, 1, 0, 'C', true);
        $pdf->Cell(10, 8, $desertores_var, 1, 0, 'C', true);
        $pdf->Cell(10, 8, $desertores_tot, 1, 0, 'C', true);
        $pdf->Cell(10, 8, $traslados_hem, 1, 0, 'C', true);
        $pdf->Cell(10, 8, $traslados_var, 1, 0, 'C', true);
        $pdf->Cell(10, 8, $traslados_tot, 1, 1, 'C', true);
        $pdf->SetFillColor(250, 250, 250);
        $x = $pdf->GetX();
        $y = $pdf->GetY();
        $pdf->SetXY($x, $y+2);
        $pdf->Cell(15, 10, 'Numero', 1, 0, 'C', true);
        $pdf->Cell(60, 10, 'Nombre del Docente', 1, 0, 'C', true);
        $pdf->Cell(40, 10, 'Cargo', 1, 0, 'C', true);
        $pdf->Cell(20, 10, 'Grado', 1, 0, 'C', true);
        $pdf->MultiCell(30, 10, 'N° de Alumnos Por Seccion', 1, 0, 'C', true);
        $x = $pdf->GetX();
        $y = $pdf->GetY();
        $pdf->SetXY($x, $y - 10);
        $pdf->Cell(60, 5, 'Inasistencias', 1, 0, 'C', true);
        $x = $pdf->GetX();
        $y = $pdf->GetY();
        $pdf->SetXY($x-60, $y+5);
        $pdf->Cell(20, 5, 'Autorizados', 1, 0, 'C', true);
        $pdf->Cell(25, 5, 'No Autorizados', 1, 0, 'C', true);
        $pdf->Cell(15, 5, 'Total', 1, 0, 'C', true);
        $x = $pdf->GetX();
        $y = $pdf->GetY();
        $pdf->SetXY($x, $y-5);
        $pdf->Cell(60, 10, 'Observaciones', 1, 1, 'C', true);
        foreach ($docentes as $docente){
            $pdf->Cell(15, 10, $docente['numero'], 1, 0, 'C', true);
            $pdf->Cell(60, 10, $docente['nombre'], 1, 0, 'C', true);
            $pdf->Cell(40, 10, $docente['cargo'], 1, 0, 'C', true);
            $pdf->Cell(20, 10, $docente['grado'], 1, 0, 'C', true);
            $pdf->Cell(30, 10, $docente['n_alumnos'], 1, 0, 'C', true);
            $pdf->Cell(20, 10, $docente['inasistencia_autorizadas'], 1, 0, 'C', true);
            $pdf->Cell(25, 10, $docente['inasistencias_autorizadas'], 1, 0, 'C', true);
            $pdf->Cell(15, 10, $docente['total_inasistencia'], 1, 0, 'C', true);
            $pdf->Cell(60, 10, $docente['Observaciones'], 1, 1, 'C', true);        
        }
    }
    $pdf->ln(15);
    $pdf->Cell(160, 5, $centro[0]['Direccion'], 0, 0, 'L', true);
    $pdf->Cell(80, 5, "Director(a) de Centro Educativo", 'T', 0, 'C', false);
    $pdf->Output('mi_pdf.pdf', 'I');
